# DeepBlue RAG System Configuration

# Embedding Models
embeddings:
  default: "sentence-transformers/all-MiniLM-L6-v2"
  options:
    - "sentence-transformers/all-mpnet-base-v2"
    - "sentence-transformers/all-MiniLM-L12-v2"
    - "openai/text-embedding-ada-002"
    - "cohere/embed-english-v3.0"

# Vector Stores
vector_stores:
  default: "chroma"
  options:
    - "pinecone"
    - "weaviate"
    - "qdrant"
    - "faiss"
    - "chroma"

# LLM Providers
llm_providers:
  default: "openai"
  options:
    - "openai"
    - "anthropic"
    - "ollama"
    - "huggingface"

# Models
models:
  openai:
    - "gpt-4"
    - "gpt-4-turbo"
    - "gpt-3.5-turbo"
  anthropic:
    - "claude-3-opus"
    - "claude-3-sonnet"
    - "claude-3-haiku"
  ollama:
    - "llama2"
    - "mistral"
    - "codellama"

# Reranking
rerankers:
  default: "cross-encoder"
  options:
    - "cross-encoder"
    - "bge-reranker"
    - "cohere-rerank"

# Chunking
chunking:
  default_size: 1000
  default_overlap: 200
  strategies:
    - "recursive"
    - "semantic"
    - "fixed"

# Retrieval
retrieval:
  default_top_k: 10
  rerank_top_k: 5
  hybrid_alpha: 0.7

# Generation
generation:
  default_temperature: 0.7
  max_tokens: 1000
  streaming: true
